
name: Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "Tests go here, customize if needed"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root
            if [ ! -d Vault2025 ]; then git clone https://github.com/AK478-dev/Vault2025.git; fi
            cd Vault2025
            git pull origin main
            pip install -r requirements.txt
            # (add more commands if you want)

  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest || echo "No tests found, skipping."
      - name: Deploy
        run: |
          echo "Insert your deployment script or command here"
run: |
          echo "Tests go here, customize if needed"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root
            if [ ! -d Vault2025 ]; then git clone https://github.com/AK478-dev/Vault2025.git; fi
            cd Vault2025
            git pull origin main
            pip install -r requirements.txt
            # (add more commands if you want)

