name: Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root
            if [ ! -d Vault2025 ]; then git clone https://github.com/AK478-dev/Vault2025.git; fi
            cd Vault2025
            git pull origin main
            pip install -r requirements.txt
