name: Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (GitHub runner only)
        run: pip install -r requirements.txt

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root
            if [ ! -d Vault2025 ]; then
              git clone https://github.com/AK478-dev/Vault2025.git
            fi
            cd Vault2025
            git pull origin main
            apt-get update
            apt-get install -y python3-pip
            pip3 install --break-system-packages --ignore-installed --force-reinstall -r requirements.txt
